### ISSUE TITLE
printAll()

### ISSUE THREAD

**Issue by gavinking** [jvasileff/ceylon-dart#1]
Given:

```ceylon
printAll { for (i in 0..10) i^2 };
```

I get:

```
0Unhandled exception:
type 'dart$Default' is not a subtype of type 'String' in type cast.
#0      Object._as (dart:core-patch/object_patch.dart:70)
#1      $package$printAll.<anonymous closure> (package:ceylon/language/language.dart:9655:46)
#2      Iterable.$each (package:ceylon/language/language.dart:4652:22)
#3      functionIterable$$anonymous$0_.each (package:ceylon/language/language.dart:1142:44)
#4      $package$printAll (package:ceylon/language/language.dart:9651:12)
#5      printAll (package:ceylon/language/language.dart:9662:90)
#6      $package$run.<anonymous closure> (file:///var/folders/3l/_1gb8m1n51j9_tc07h0lflr40000gn/T/ceylon-run-dart5767981372227819311/hello/hello.dart:53:16)
#7      $package$run (file:///var/folders/3l/_1gb8m1n51j9_tc07h0lflr40000gn/T/ceylon-run-dart5767981372227819311/hello/hello.dart:54:7)
#8      run (file:///var/folders/3l/_1gb8m1n51j9_tc07h0lflr40000gn/T/ceylon-run-dart5767981372227819311/hello/hello.dart:57:15)
#9      main (file:///var/folders/3l/_1gb8m1n51j9_tc07h0lflr40000gn/T/ceylon-run-dart5767981372227819311/hello/hello.dart:61:5)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

It works with plain `print()`.

**Comment by jvasileff** [comment]
The workaround is to not use named-args:
```ceylon
printAll({for (i in 0..10) i^2});
```

Strange. An explicitly passed default value indicator in one module for some reason isn't `identical` to the default value indicator in the language module. In the compiled example:
```
return $ceylon$language.printAll(arg$0$0, $ceylon$language.dart$default);
```
and in `printAll`
```
    if ($dart$core.identical(separator, $package$dart$default)) {
        separator = ", ";
    }
```

**Comment by jvasileff** [comment]
Maybe a bug in my handwritten Dart code, if don't understand Dart's `const` keyword:

```
class dart$Default {
  const dart$Default();
}

const dart$default = const dart$Default();

const $package$dart$default = dart$Default;
```

**Comment by jvasileff** [comment]
Fixed, thanks!

**Comment by gavinking** [comment]
Thanks!
