### ISSUE TITLE
Future.then(...) doesn't like the result of uncurry

### ISSUE THREAD

**Issue by jvasileff** [jvasileff/ceylon-dart#14]
This works:
```ceylon
HttpClientResponse response = await (client.getUrl(url)
    .\ithen((hcr) => uncurry(HttpClientRequest.close)(hcr)));
```
but not:
```ceylon
HttpClientResponse response = await (client.getUrl(url)
    .\ithen(uncurry(HttpClientRequest.close)));
```
```
Unhandled exception:
Closure call with mismatched arguments: function 'call'

NoSuchMethodError: method not found: 'call'
Receiver: Instance of 'dart$FlatFunction'
Arguments: [Instance of '_HttpClientRequest']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      dart$FlatFunction.noSuchMethod (package:ceylon/language/language.dart:15068:25)
#3      _RootZone.runUnary (dart:async/zone.dart:1204)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#7      _Future._completeWithValue (dart:async/future_impl.dart:477)
#8      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by jvasileff** [comment]
Fixed!
